name: Integration Tests
on:   
  push:
  repository_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  Integration_Tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Print the stuff in the directory
        run: ls
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build      
