name: Integration Tests
on:   
  repository_dispatch:
jobs:
  Integration_Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Grant execute permission for gradlew
        run: chmod +x Integration_Test/gradlew
      - name: Build with Gradle
        run: cd Integration_Test && ./gradlew build      
